version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
    networks:
      - divulgatudonetwork
  app-divulga-tudo:
    image: projeto-divulga-tudo
    container_name: "app-divulga-tudo"
    ports:
     - 8080:8080 
    networks:
      - divulgatudonetwork 
networks:
  divulgatudonetwork:
    driver: bridge